kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service-monitoring
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: NodePort
  selector:
    app: train-schedule-monitoring
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8082

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment-monitoring
  labels:
    app: train-schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule-monitoring
  template:
    metadata:
      labels:
        app: train-schedule-monitoring
    spec:
      containers:
      - name: train-schedule-monitoring
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
	  requests:
	    cpu: 200m

---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: train-schedule-monitoring
  namespace: default
spec:
  scaleTargetRef:
  apiVersion: apps/v1
  kind: Deployment
  name: train-schedule-deployment-monitoring
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resources
    resources:
      name: cpu
      targetAverageUtilization:50
